@startuml
package com.yonatankarp.factory.method {
  class App {
    + main(args : String[]) {static}
  }

  class Money {
    + dollars(amount: Int) {static}
    + euros(amount: Int) {static}
    + toString()
    - Money(amount: Int, currency: String)
  }

  App --> "money" Money
  Money -->  "-dollars" Money
  Money -->  "-euro" Money
}
@enduml
