@startuml
package com.yonatankarp.singleton {
  class App {
    - LOGGER : Logger {static}
    + App()
    + main(args : String[]) {static}
  }
  object IvoryTower {
    - IvoryTower()
    + getInstance() : IvoryTower {static}
  }
}
IvoryTower -->  "-INSTANCE" IvoryTower
@enduml
