name: Markdown Linter

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linters:
    uses: yonatankarp/github-actions/.github/workflows/linters.yml@v2
    with:
      check_style: false
