name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Build & Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build

  dependabot-auto-merge:
    needs: build
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v1
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}