name: Continuous Integration

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    strategy:
      matrix:
        module: [
          "abstract-factory",
          "adapter",
          "bridge",
          "builder",
          "chain-of-responsibility",
          "command",
          "composite",
          "decorator",
          "facade",
          "factory",
          "factory-method",
          "flyweight",
          "iterator",
          "mediator",
          "observer",
          "prototype",
          "proxy",
          "singleton",
          "state",
          "strategy",
          "template-method",
          "visitor",
        ]
    uses: yonatankarp/github-actions/.github/workflows/ci.yml@v1
    with:
      context: ${{ matrix.module }}
      app_name: ${{ matrix.module }}

  pipeline-check:
    if: |
      github.event_name == 'pull_request_target' ||
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether all CI jobs are succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  dependabot_auto_merge:
    needs: pipeline
    if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v1

  linters:
    uses: yonatankarp/github-actions/.github/workflows/linters.yml@v1
